//! Automatic shell integration for local sessions.
//!
//! Command history depends on OSC 133 markers, which only exist if the shell
//! emits them. Rather than asking the user to paste a snippet into their rc
//! file, we start the shell with a generated init that sources their real
//! config first and then appends our hooks.
//!
//! The hard requirement is **transparency**: the user's own prompt, aliases,
//! and options must survive untouched. If anything here fails we fall back to
//! a plain shell -- losing history is acceptable, breaking someone's shell is
//! not.

use crate::OSC133_BASH_ZSH;
use anyhow::Result;
use std::path::{Path, PathBuf};

/// How to launch a shell with integration enabled.
pub struct ShellInit {
    /// Extra arguments to pass to the shell.
    pub args: Vec<String>,
    /// Environment overrides.
    pub env: Vec<(String, String)>,
    /// Scratch directory holding generated rc files; removed on drop.
    dir: PathBuf,
}

impl Drop for ShellInit {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.dir);
    }
}

/// Which shell family we are dealing with, by executable name.
fn family(program: &str) -> Option<&'static str> {
    let name = Path::new(program)
        .file_stem()
        .and_then(|s| s.to_str())
        .unwrap_or(program);
    match name {
        "bash" => Some("bash"),
        "zsh" => Some("zsh"),
        _ => None,
    }
}

/// Build the integration files for `program`, or `None` if unsupported.
///
/// `scratch` is a session-scoped directory; the caller owns its lifetime only
/// insofar as the returned value keeps it alive.
pub fn prepare(program: &str, scratch: &Path) -> Result<Option<ShellInit>> {
    let Some(fam) = family(program) else {
        return Ok(None);
    };
    std::fs::create_dir_all(scratch)?;

    match fam {
        "bash" => Ok(Some(prepare_bash(scratch)?)),
        "zsh" => Ok(Some(prepare_zsh(scratch)?)),
        _ => Ok(None),
    }
}

/// bash: `--rcfile` replaces `~/.bashrc` for interactive shells, so the
/// generated file must source the user's own config before adding hooks.
///
/// Note `--rcfile` is **ignored for login shells**, which read `~/.bash_profile`
/// instead. So we deliberately drop `-l` and emulate it by sourcing the
/// profile ourselves -- otherwise integration would silently never load.
fn prepare_bash(dir: &Path) -> Result<ShellInit> {
    let home = home_dir();
    let rc = dir.join("bash-init.sh");

    let mut s = String::new();
    s.push_str("# Generated by Terminator. Sources your config, then adds OSC 133 hooks.\n");
    // Login-shell equivalence: system profile first, then the first
    // user profile that exists, matching bash's own precedence.
    s.push_str("[ -f /etc/profile ] && . /etc/profile\n");
    s.push_str(&format!(
        "for __f in \"{h}/.bash_profile\" \"{h}/.bash_login\" \"{h}/.profile\"; do\n  \
           if [ -f \"$__f\" ]; then . \"$__f\"; break; fi\n\
         done\n\
         unset __f\n",
        h = sh_quote_path(&home)
    ));
    // A non-login interactive bash would normally read .bashrc; many profiles
    // already source it, and sourcing twice is common practice and harmless.
    s.push_str(&format!(
        "[ -f \"{h}/.bashrc\" ] && . \"{h}/.bashrc\"\n",
        h = sh_quote_path(&home)
    ));
    s.push_str(OSC133_BASH_ZSH);
    std::fs::write(&rc, s)?;

    Ok(ShellInit {
        args: vec![
            "--rcfile".into(),
            rc.to_string_lossy().into_owned(),
            "-i".into(),
        ],
        env: Vec::new(),
        dir: dir.to_path_buf(),
    })
}

/// zsh has no `--rcfile`, so the supported approach is to point `ZDOTDIR` at a
/// directory of our own. zsh reads *four* files from it, so all four must be
/// forwarded or we would silently drop the user's `.zprofile`/`.zlogin`.
///
/// Subtlety that is easy to get wrong: zsh re-reads `$ZDOTDIR` before **each**
/// startup file. Restoring it permanently in `.zshenv` (the first file) means
/// every later file is read from the user's directory instead of ours, so our
/// hooks never load at all. Instead we keep `ZDOTDIR` pointed at our directory
/// for the whole sequence, flipping it to the real value only while sourcing
/// the user's file, and restore it for good in the last file that runs.
fn prepare_zsh(dir: &Path) -> Result<ShellInit> {
    let user_zdotdir = std::env::var("ZDOTDIR").ok().unwrap_or_else(home_dir);
    let ours = sh_quote_path(&dir.to_string_lossy());

    for name in [".zshenv", ".zprofile", ".zshrc", ".zlogin"] {
        let mut s = String::new();
        s.push_str("# Generated by Terminator. Forwards to your real zsh config.\n");
        // Point at the user's dir so their config sees its own ZDOTDIR, then
        // hand it straight back so zsh finds the next file here.
        s.push_str("__terminator_user=\"${__TERMINATOR_ZDOTDIR}\"\n");
        s.push_str("ZDOTDIR=\"$__terminator_user\"\n");
        s.push_str(&format!(
            "[ -f \"$__terminator_user/{name}\" ] && . \"$__terminator_user/{name}\"\n"
        ));
        // The user's config may legitimately reassign ZDOTDIR; respect that.
        s.push_str("__TERMINATOR_ZDOTDIR=\"$ZDOTDIR\"\n");

        if name == ".zshrc" {
            // Repoint HISTFILE at the user's directory.
            //
            // macOS's /etc/zshrc does `HISTFILE=${ZDOTDIR:-$HOME}/.zsh_history`,
            // and it runs while ZDOTDIR still points at our scratch dir -- so
            // history would be read from, and saved to, a directory we delete
            // when the session ends. The user would lose their history and see
            // an empty one on every launch.
            //
            // Only rewrite it if it still points inside our scratch dir: if the
            // user's own config chose a HISTFILE, that choice wins.
            //
            // Setting it here is enough. zsh reads the history file lazily at
            // the first prompt, which is after .zshrc, so an explicit `fc -R`
            // is not needed -- and actively harmful, since it loads the file a
            // second time and duplicates every entry.
            s.push_str(&format!(
                "if [[ \"$HISTFILE\" == \"{ours}\"/* ]]; then\n  \
                   HISTFILE=\"$__terminator_user/.zsh_history\"\n\
                 fi\n"
            ));
            // Hooks belong in the interactive rc, after the user's prompt setup.
            s.push_str(OSC133_BASH_ZSH);
        }

        if name == ".zlogin" {
            // Last file in the sequence: stop redirecting.
            s.push_str("unset __terminator_user\n");
        } else {
            s.push_str(&format!("ZDOTDIR=\"{ours}\"\n"));
        }
        std::fs::write(dir.join(name), s)?;
    }

    Ok(ShellInit {
        // -l so .zlogin runs and the sequence terminates cleanly above.
        args: vec!["-l".into(), "-i".into()],
        env: vec![
            ("ZDOTDIR".into(), dir.to_string_lossy().into_owned()),
            ("__TERMINATOR_ZDOTDIR".into(), user_zdotdir),
        ],
        dir: dir.to_path_buf(),
    })
}

fn home_dir() -> String {
    std::env::var("HOME")
        .or_else(|_| std::env::var("USERPROFILE"))
        .unwrap_or_else(|_| "/".into())
}

/// Escape a path for safe interpolation inside a double-quoted shell string.
fn sh_quote_path(p: &str) -> String {
    p.replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('$', "\\$")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn scratch(tag: &str) -> PathBuf {
        std::env::temp_dir().join(format!("terminator-shell-init-test-{tag}"))
    }

    /// Regression: macOS's /etc/zshrc sets HISTFILE from ZDOTDIR, which points
    /// at our scratch dir while it runs. Without a fixup the user's history is
    /// read from, and written to, a directory we delete on session end.
    #[test]
    fn zsh_rc_repoints_histfile_out_of_scratch() {
        let dir = scratch("histfile");
        let _ = std::fs::remove_dir_all(&dir);
        let init = prepare("/bin/zsh", &dir).unwrap().unwrap();

        let rc = std::fs::read_to_string(dir.join(".zshrc")).unwrap();
        assert!(
            rc.contains("HISTFILE=\"$__terminator_user/.zsh_history\""),
            "generated .zshrc must move HISTFILE back to the user's dir:\n{rc}"
        );
        // Guarded, so a HISTFILE the user chose themselves is left alone.
        assert!(
            rc.contains("if [[ \"$HISTFILE\" =="),
            "fixup must be conditional"
        );
        // `fc -R` here would load the history file a second time and duplicate
        // every entry; zsh reads it lazily after .zshrc on its own.
        assert!(
            !rc.contains("fc -R"),
            "must not force a second history read"
        );

        drop(init);
    }

    /// The fixup belongs only in the interactive rc.
    #[test]
    fn zsh_histfile_fixup_only_in_zshrc() {
        let dir = scratch("histfile-scope");
        let _ = std::fs::remove_dir_all(&dir);
        let init = prepare("/bin/zsh", &dir).unwrap().unwrap();

        for other in [".zshenv", ".zprofile", ".zlogin"] {
            let s = std::fs::read_to_string(dir.join(other)).unwrap();
            assert!(!s.contains("HISTFILE"), "{other} should not touch HISTFILE");
        }

        drop(init);
    }

    /// bash keeps its own default (~/.bash_history) because we never move HOME,
    /// so it must not grow a fixup it doesn't need.
    #[test]
    fn bash_init_sources_user_config() {
        let dir = scratch("bash");
        let _ = std::fs::remove_dir_all(&dir);
        let init = prepare("/bin/bash", &dir).unwrap().unwrap();

        let rc = std::fs::read_to_string(dir.join("bash-init.sh")).unwrap();
        assert!(rc.contains(".bashrc"), "must source the user's bashrc");
        assert!(!rc.contains("HISTFILE"), "bash needs no HISTFILE fixup");
        assert!(init.args.contains(&"--rcfile".to_string()));

        drop(init);
    }

    /// Scratch files are session-scoped and must not outlive the session.
    #[test]
    fn scratch_dir_removed_on_drop() {
        let dir = scratch("cleanup");
        let _ = std::fs::remove_dir_all(&dir);
        let init = prepare("/bin/zsh", &dir).unwrap().unwrap();
        assert!(dir.exists());
        drop(init);
        assert!(!dir.exists(), "scratch dir must be cleaned up");
    }
}
